
import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Share2, Loader2, Download, Clipboard } from "lucide-react";

import { useToast } from "@/components/ui/use-toast";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export default function ShareLinkModal({ vehicle, onClose }) {
  const [expiry, setExpiry] = useState('30');
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  // Helper to create a public URL (assuming it's a relative path that needs base URL)
  // This function is not defined in the outline, so a plausible one is created.
  const createPageUrl = (path) => {
    if (path.startsWith('PublicVehicleView?id=')) {
      const vehicleId = path.split('=')[1];
      return `/public/vehicle/${vehicleId}`;
    }
    return `/${path}`; // Generic fallback
  };

  const publicUrl = `${window.location.origin}${createPageUrl(`PublicVehicleView?id=${vehicle.id}`)}`;

  const copyToClipboard = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast({ title: "Copied!", description: "Link copied to clipboard." });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy link:', error);
      toast({ title: "Error", description: "Failed to copy link.", variant: "destructive" });
    }
  };
  
  const generatePdf = async () => {
    setIsGenerating(true);
    toast({ title: "Generating PDF...", description: "Please wait while we prepare your document." });

    // Create a temporary element to render the VDP for PDF generation
    const printableElement = document.createElement('div');
    printableElement.style.position = 'absolute';
    printableElement.style.left = '-9999px';
    printableElement.style.width = '800px'; // A standard page width for rendering
    printableElement.innerHTML = `
      <div class="p-8 font-sans bg-white text-black">
        <h1 class="text-2xl font-bold">${vehicle.year} ${vehicle.make} ${vehicle.model}</h1>
        <p class="text-slate-600">${vehicle.variant || ''}</p>
        <div class="mt-4 grid grid-cols-2 gap-4">
          <div><strong class="font-medium">Price:</strong> ₹${(vehicle.asking_price / 100000).toFixed(1)}L</div>
          <div><strong class="font-medium">KMs:</strong> ${vehicle.kilometers ? vehicle.kilometers.toLocaleString() : 'N/A'}</div>
          <div><strong class="font-medium">Fuel:</strong> ${vehicle.fuel_type || 'N/A'}</div>
          <div><strong class="font-medium">Ownership:</strong> ${vehicle.ownership || 'N/A'}</div>
        </div>
        <p class="mt-4 text-sm">${vehicle.description || ''}</p>
        <p class="mt-8 text-xs text-slate-400">Generated by Aura Dealer Network</p>
      </div>
    `;
    document.body.appendChild(printableElement);

    try {
      const canvas = await html2canvas(printableElement, {
        useCORS: true,
        scale: 2, // Increase resolution for better PDF quality
        backgroundColor: '#ffffff' // Ensure background is white
      });
      const imgData = canvas.toDataURL('image/png');
      
      const pdf = new jsPDF({
        orientation: 'p',
        unit: 'px',
        format: [canvas.width, canvas.height]
      });
      
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      
      const filename = `${vehicle.make}_${vehicle.model}_${vehicle.registration_number || vehicle.id || 'vehicle'}.pdf`;
      pdf.save(filename);
      
      toast({ title: "✓ PDF Generated", description: "Your PDF has been downloaded." });
    } catch (error) {
      console.error("PDF Generation failed:", error);
      toast({ title: "Error", description: "Could not generate PDF.", variant: "destructive" });
    } finally {
      document.body.removeChild(printableElement);
      setIsGenerating(false);
    }
  };


  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Share2 className="w-5 h-5 text-blue-600" />
            Share Vehicle
          </DialogTitle>
          <DialogDescription>
            {vehicle.year} {vehicle.make} {vehicle.model}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Expiry Settings */}
          <div className="space-y-2">
            <Label>Link Expires In</Label>
            <Select value={expiry} onValueChange={setExpiry}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1 Day</SelectItem>
                <SelectItem value="7">7 Days</SelectItem>
                <SelectItem value="30">30 Days</SelectItem>
                <SelectItem value="90">90 Days</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex gap-3">
            <Button
              variant="outline"
              onClick={generatePdf}
              disabled={isGenerating}
              className="flex-1"
            >
              {isGenerating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Download className="w-4 h-4 mr-2" />}
              {isGenerating ? 'Generating...' : 'Download PDF'}
            </Button>
            <Button onClick={() => copyToClipboard(publicUrl)} className="flex-1">
              <Clipboard className="w-4 h-4 mr-2" />
              Copy Link
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
