// Import from Supabase adapters instead of Base44
import {
  Dealer,
  Vehicle,
  VehicleAsset,
  VehicleDocument,
  Transaction,
  Payment,
  LogisticsOrder,
  RTOApplication,
  BankAccount,
  BankDetails,
  DealerPreferences,
  UserSession,
  TeamMember,
  DealerDocument,
  DealerHours,
  DealerReview,
  DealerRating,
  DealerInquiry,
  AuditLog,
  Shortlist,
  VehicleInspection,
  VehicleCondition,
  Branch,
  AppConfig,
  User
} from './entityAdapters';

// Re-export all entities to maintain the same interface
export {
  Dealer,
  Vehicle,
  VehicleAsset,
  VehicleDocument,
  Transaction,
  Payment,
  LogisticsOrder,
  RTOApplication,
  BankAccount,
  BankDetails,
  DealerPreferences,
  UserSession,
  TeamMember,
  DealerDocument,
  DealerHours,
  DealerReview,
  DealerRating,
  DealerInquiry,
  AuditLog,
  Shortlist,
  VehicleInspection,
  VehicleCondition,
  Branch,
  AppConfig,
  User
};

